# biped.controllers.yaml

controller_manager:
    ros__parameters:
        use_sim_time: true
        update_rate: 100

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        forward_position_controller:
            type: position_controllers/JointGroupPositionController

forward_position_controller:
    ros__parameters:
        joints:
            - left_hip_knee_joint_1
            - left_hip_knee_joint_2
            - left_ankle_joint
            - right_hip_knee_joint_1
            - right_hip_knee_joint_2
            - right_ankle_joint
        interface_name: position
